name: Deploy to EC2

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ec2-13-53-97-124.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Connect to EC2 and deploy
      run: |
        ssh ubuntu@ec2-13-53-97-124.eu-north-1.compute.amazonaws.com << 'EOF'
          echo "Connected to EC2"
          cd ~/JobRecruitment/Full-Stack-Project-Dockerization
          echo "Changed to project directory"
          git pull origin main
          echo "Pulled latest changes"
          sudo docker compose down
          echo "Docker Compose down"
          sudo docker compose up --build -d
          echo "Docker Compose up completed"
        EOF
