name: Deploy Application to EC2

on:
  push:
    branches:
      - main  # or replace with your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -H ubuntu@ec2-13-53-97-124.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2 via SSH
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@ec1234.eu-north-1.compute.amazonaws.com << 'EOF'
          echo "Connected to EC2 successfully!"
          EOF
